fix some typos
SkyCraft78/DiSky pull request #70
Opened 2021-08-02 00:20 UTC by wallace4BR

2021-08-02 17:56 UTC, Mushkrem requested changes

2021-08-02 17:56 UTC, Mushkrem commented on src/main/java/info/itsthesky/DiSky/managers/cache/EditedMessages.java
> +                if (Utils.INFO_CACHE) DiSky.getInstance().getLogger().info("Starting cache of "message edit" event for guild " + guild.getName() + "...");
if (Utils.INFO_CACHE) DiSky.getInstance().getLogger().info("Starting cache of \"message edit\" event for guild " + guild.getName() + "...");

2021-08-02 17:56 UTC, Mushkrem commented on src/main/java/info/itsthesky/DiSky/managers/cache/EditedMessages.java
> +                        if (Utils.INFO_CACHE) DiSky.getInstance().getLogger().warning("DiSky cannot cache messages for "message edit" event since the bot doesn't have the " + ex.getPermission().getNa
if (Utils.INFO_CACHE) DiSky.getInstance().getLogger().warning("DiSky cannot cache messages for \"message edit\" event since the bot doesn't have the " + ex.getPermission().getName() + " permission!");

2021-08-02 17:56 UTC, Mushkrem commented on src/main/java/info/itsthesky/DiSky/managers/cache/EditedMessages.java
> +                if (Utils.INFO_CACHE) DiSky.getInstance().getLogger().info("Finished caching messages for "message edit" event for guild " + guild.getName() + "! Took " + (start - System.currentTimeM
if (Utils.INFO_CACHE) DiSky.getInstance().getLogger().info("Finished caching messages for \"message edit\" event for guild " + guild.getName() + "! Took " + (start - System.currentTimeMillis()) + "ms!");

2021-08-02 17:56 UTC, Mushkrem commented on src/main/java/info/itsthesky/DiSky/managers/cache/Messages.java
> +                if (Utils.INFO_CACHE) DiSky.getInstance().getLogger().info("Starting cache of "message delete" event for guild " + guild.getName() + "...");
if (Utils.INFO_CACHE) DiSky.getInstance().getLogger().info("Starting cache of \"message delete\" event for guild " + guild.getName() + "...");

2021-08-02 17:56 UTC, Mushkrem commented on src/main/java/info/itsthesky/DiSky/managers/cache/Messages.java
> +                        if (Utils.INFO_CACHE) DiSky.getInstance().getLogger().warning("DiSky cannot cache messages for "message delete" event, since the bot doesn't have the " + ex.getPermission().ge
if (Utils.INFO_CACHE) DiSky.getInstance().getLogger().warning("DiSky cannot cache messages for \"message delete\" event, since the bot doesn't have the " + ex.getPermission().getName() + " permission!");

2021-08-02 17:56 UTC, Mushkrem commented on src/main/java/info/itsthesky/DiSky/managers/cache/Messages.java
> +                if (Utils.INFO_CACHE) DiSky.getInstance().getLogger().info("Finished caching messages for "message delete" event for guild " + guild.getName() + ", Took " + (start - System.currentTim
if (Utils.INFO_CACHE) DiSky.getInstance().getLogger().info("Finished caching messages for \"message delete\" event for guild " + guild.getName() + ", Took " + (start - System.currentTimeMillis()) + "ms!");

2021-08-02 17:56 UTC, Mushkrem commented on src/main/java/info/itsthesky/DiSky/tools/DiSkyErrorHandler.java
> +                logger.warning("DiSky tried to build an embed, however, there aren't any title, author or description! (The embed is empty)");
logger.warning("DiSky tried to build an embed, however, there is no title, author nor description! (The embed is empty)");

2021-08-02 18:51 UTC, WeeskyBDW approved these changes
LGTM for text changes but i see a lot of similiar messages, that imo need to be grouped

2021-08-02 21:02 UTC, SkyCraft78 approved these changes
SGTM, thanks you 😊

2021-08-02 21:02 UTC, Mushkrem approved these changes

2021-08-02 21:03 UTC, SkyCraft78 commented
Oh, it look likes the buil didn't finished correctly 😟
Please fix it before I can merge the PR 😄

2021-08-02 21:07 UTC, Mushkrem approved these changes

2021-08-02 21:09 UTC, Mushkrem requested changes

2021-08-02 21:09 UTC, Mushkrem commented on src/main/java/info/itsthesky/DiSky/managers/cache/Messages.java
> +                if (Utils.INFO_CACHE) DiSky.getInstance().getLogger().info("Starting cache of "message delete" event for guild " + guild.getName() + "...");
```suggestion
                if (Utils.INFO_CACHE) DiSky.getInstance().getLogger().info("Starting cache of \"message delete\" event for guild " + guild.getName() + "...");
```

2021-08-02 21:09 UTC, Mushkrem commented on src/main/java/info/itsthesky/DiSky/managers/cache/Messages.java
> +                        if (Utils.INFO_CACHE) DiSky.getInstance().getLogger().warning("DiSky cannot cache messages for "message delete" event, since the bot doesn't have the " + ex.getPermission().ge
```suggestion
                        if (Utils.INFO_CACHE) DiSky.getInstance().getLogger().warning("DiSky cannot cache messages for \"message delete\" event, since the bot doesn't have the " + ex.getPermission().getName() + " permission!");
```

2021-08-02 21:09 UTC, Mushkrem commented on src/main/java/info/itsthesky/DiSky/managers/cache/EditedMessages.java
> +                        if (Utils.INFO_CACHE) DiSky.getInstance().getLogger().warning("DiSky cannot cache messages for "message edit" event since the bot doesn't have the " + ex.getPermission().getNa
```suggestion
                        if (Utils.INFO_CACHE) DiSky.getInstance().getLogger().warning("DiSky cannot cache messages for \"message edit\" event since the bot doesn't have the " + ex.getPermission().getName() + " permission!");
```

2021-08-02 21:19 UTC, Mushkrem requested changes

2021-08-02 21:19 UTC, Mushkrem commented on src/main/java/info/itsthesky/DiSky/managers/cache/InviteTracker.java
> +                if (Utils.INFO_CACHE) DiSky.getInstance().getLogger().severe("DiSky cannot cache invites for \"event-invite\" value in \"member join\" event for guild '"+guild.getName()+"', since the
```suggestion
                if (Utils.INFO_CACHE) DiSky.getInstance().getLogger().severe("DiSky cannot cache invites for \"event-invite\" value in \"member join\" event for guild '"+guild.getName()+"', since the bot doesn't have the: " + e.getPermission().getName() + " permission!");
```

2021-08-02 21:25 UTC, wallace4BR commented
> Oh, it look likes the buil didn't finished correctly 
> Please fix it before I can merge the PR

my bad, first time doing an PR and i've already mess up everything XD
it should be fine now

2021-08-03 19:40 UTC, SkyCraft78 approved these changes

2021-08-03 21:20 UTC, merged